// <auto-generated />
namespace BankingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialCreationV3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialCreationV3));
        
        string IMigrationMetadata.Id
        {
            get { return "202205210606064_initialCreationV3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
